mqtt:
  - broker: "tls://agi8wtqgu97at-ats.iot.ap-southeast-2.amazonaws.com"
    port: 8883
    topic: "pfd/ot/water"
    ca: "./certificates/ca.pem"
    cert: "./certificates/certificate.pem.crt"
    key: "./certificates/private.pem.key"

mbusModbus:
  gatewayAddress: "10.129.195.98:502"
  pollInterval: 60
  totalBlocks: 10


modbus:
  tcp_port: "502"
